Numpy Assignment

##  1. What is a Python library? Why do we use Python libraries?
-->  A Python library is a collection of pre-written code and functions that developers can use to perform specific tasks without having to write the code from scratch. These libraries often contain modules that provide functionalities such as mathematical operations, data manipulation, web development, machine learning algorithms, and much more.. Some popular Python libraries include NumPy for numerical computing, Pandas for data analysis, Matplotlib for data visualization, TensorFlow for machine learning, and Flask for web development.
Libraries provide pre-written code for common tasks, saving developers time and effort. Libraries offer a wide range of functionalities, covering various domains such as mathematics, data analysis, machine learning, web development, and more.Many Python libraries are designed to handle large datasets and complex computations efficiently.Python has a vibrant and active community of developers who contribute to the development and maintenance of libraries.

##  2. What is the difference between Numpy array and List?
--> NumPy arrays are more memory-efficient compared to Python lists. NumPy arrays store homogeneous data types, which means all elements in the array must have the same data type.
-->  NumPy arrays offer better performance for numerical computations compared to Python lists.
-->  NumPy arrays provide a wide range of mathematical functions and operations for array manipulation, such as element-wise operations, linear algebra operations, Fourier transforms, and more.
-->  NumPy arrays support advanced indexing and slicing operations, allowing you to access and manipulate elements of the array efficiently.
-->  NumPy arrays support vectorized operations, which allow you to perform operations on entire arrays without using explicit loops.

In [2]:
##  3. Find the shape, size an^d dimension of the following array?

'''[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]'''
import numpy as np
arr1 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("Array :",arr1)
print("The shape of array :",arr1.shape)
print("The size of the array :",arr1.size)
print("The dimension of the array :",arr1.ndim)


Array : [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
The shape of array : (3, 4)
The size of the array : 12
The dimension of the array : 2


In [3]:
##  4. Write python co^e to access the first row of the following array?

'''[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]'''
import numpy as np
arr2 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("Array :",arr2)
print("The access of the first row of the array :",arr2[0])

Array : [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
The access of the first row of the array : [1 2 3 4]


In [5]:
##  5. How do you access the element at the third row and fourth column from the given numpy array?

'''[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]'''
import numpy as np
arr2 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("Array :",)
print("The element at the third row and fourth column is :",arr2[2,3])

Array :
The element at the third row and fourth column is : 12


In [6]:
##  6. Write code to extract all odd-indexed elements from the given numpy array?

'''[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]'''
import numpy as np
arr3 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("Array :",arr3)
print("Odd indexed elements are :",arr3[: ,1::2])


Array : [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Odd indexed elements are : [[ 2  4]
 [ 6  8]
 [10 12]]


In [17]:
##  7. How can you generate a random 3x3 matrix with values between 0 and 1?
import numpy as np
import random
random_matrix = np.random.rand(3,3)
print("Random matrix of 3 * 3 size with values between 0 and 1")
print(random_matrix)

Random matrix of 3 * 3 size with values between 0 and 1
[[0.66898234 0.90350519 0.87524041]
 [0.19420414 0.23970719 0.35998525]
 [0.34856409 0.61612486 0.06930543]]


##  8. Describe the difference between np.random.rand and np.random.randn?
--> np.random.rand generates random numbers from a uniform distribution within a specified range "[0.0,1.0)", while np.random.randn generates random numbers from a standard normal distribution with mean 0 and standard deviation 1.

In [20]:
9. Write code to increase the dimension of the following array?

'''[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]'''
import numpy as np
arr4 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
increase_dims = np.expand_dims(arr4,axis = 0)
print("The dimension can inrease by using .expand_dims() function and arr4 dimension is increases :")
print(increase_dims)
print("Arr4 dimension change from 2D to 3D ")


Object `array` not found.
The dimension can inrease by using .expand_dims() function and arr4 dimension is increases :
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]
Arr4 dimension change from 2D to 3D 


In [22]:
##  10. How to transpose the following array in NumPy?

'''[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]'''
import numpy as np
arr5 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("Original matrix :")
print(arr5)
print("The transpose of the matrix is :")
print(arr5.T)

Original matrix :
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
The transpose of the matrix is :
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


In [33]:
##  11. Consider the following matrix:

'''Matrix A2 [[1, 2, 3, 4], [5, 6, 7, 8],[9, 10, 11, 12]]

Matrix B2 [[1, 2, 3, 4], [5, 6, 7, 8],[9, 10, 11, 12]'''
arr6 = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
arr7 = np.asarray([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
print("Array 6 :")
print(arr6)
print("Array 7 :")
print(arr7)
# Perform the following operation using Python:
#  1 Index wise multiplication
print("Index wise multiplication :")
print(arr6 * arr7 )

#  2 Matrix multiplication
print("The matrix multiplication of array6 and array 8 is possible when arr7 should be transpose then :")
arr8 = arr7.T
print(arr6 @ arr8)

#  3 Add both the matrix
print("The addition of both matrix is :")
print(arr6 + arr7)

#  4 Subtract matrix B from matrix A 
print("Subtraction of the matrix B from A is :")
print(arr7 - arr6)


#  5 Divide Matrix B by A
print("The division of the matrix B by A is :")
print(arr7 / arr6)


Array 6 :
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Array 7 :
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Index wise multiplication :
[[  1   4   9  16]
 [ 25  36  49  64]
 [ 81 100 121 144]]
The matrix multiplication of array6 and array 8 is possible when arr7 should be transpose then :
[[ 30  70 110]
 [ 70 174 278]
 [110 278 446]]
The addition of both matrix is :
[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]
Subtraction of the matrix B from A is :
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
The division of the matrix B by A is :
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


##  12.  Which function in Numpy can be used to swap the byte order of an array?
-->  In NumPy, the function used to swap the byte order of an array is np.ndarray.byteswap(). This method swaps the byte order of the elements in the array in-place.

##  13.  What is the significance of the np.linalg.inv function?
--> The np.linalg.inv function in NumPy is used to compute the inverse of a square matrix. The significance of this function lies in various mathematical and computational applications.

In [2]:
##  14. What does the np.reshape function do, and how is it used?
'''The np.reshape function in NumPy is used to change the shape (dimensions)
of an array without changing its data. It allows you to rearrange the elements
of the array into a new shape while maintaining the same total number of 
elements.'''
import numpy as np

# Create a 1D array with 12 elements
arr = np.arange(12)

# Reshape the array into a 3x4 matrix
reshaped_arr = np.reshape(arr, (3, 4))

print("Original array:")
print(arr)
print("\nReshaped array:")
print(reshaped_arr)

Original array:
[ 0  1  2  3  4  5  6  7  8  9 10 11]

Reshaped array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
##  15. What is broadcasting in Numpy?
